# YAML Lint Configuration
# https://yamllint.readthedocs.io/

---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
  
  comments:
    min-spaces-from-content: 1
  
  document-start: disable
  
  new-line-at-end-of-file: enable
