name: MegaLinter

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oxsecurity/megalinter@v7.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
