name: MegaLinter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oxsecurity/megalinter@v7.7.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
